issues:
  exclude-rules:
    # disable funlen for all _test.go files
    - path: _test.go
      linters:
        - funlen

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
          - pkg: golang.org/x/xerrors
            desc: "holds the transition packages for the new Go 1.13 error values."
  funlen:
    lines: 100 # slog requires several lines, so allow up to 100 lines.
    statements: 50

linters:
  disable-all: true
  enable:
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - revive
    - staticcheck
    - stylecheck
    - unused
